apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-command-service
  labels:
    app: {{ .Release.Name }}-postgres-command-service
    repository.type: document
    repository.name: postgres
spec:
  replicas: {{ .Values.commandServiceReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres-command-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres-command-service
        repository.type: document
        repository.name: postgres
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: cdl-postgres-command-service
        image: "{{ .Values.global.imageRepositoryPath }}cdl-command-service:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/command-service","postgres"]
        env:
        {{- if eq .Values.global.communicationMethod "kafka" }}
        - name: COMMUNICATION_METHOD
          value: "kafka"
        - name: KAFKA_BROKERS
          value: {{ .Values.global.kafkaBrokers }}
        - name: KAFKA_GROUP_ID
          value: "cdl-postgres-command-service"
        {{- else if eq .Values.global.communicationMethod "amqp" }}
        - name: COMMUNICATION_METHOD
          value: "amqp"
        - name: AMQP_CONNECTION_STRING
          value: {{ .Values.global.amqpConnectionString }}
        - name: AMQP_CONSUMER_TAG
          value: "cdl-postgres-command-service"
        {{- else }}
        - name: COMMUNICATION_METHOD
          value: "grpc"
        - name: GRPC_PORT
          value: "6400"
        {{- end }}
        - name: ORDERED_SOURCES
          value: {{ .Values.inputSource }}
        - name: POSTGRES_USERNAME
          value: {{ .Values.postgresUsername }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresPassword }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgresHost }}
        - name: POSTGRES_PORT
          value: "{{ .Values.postgresPort }}"
        - name: POSTGRES_DBNAME
          value: {{ .Values.postgresDbname }}
        - name: POSTGRES_SCHEMA
          value: {{ .Values.postgresSchema }}
        - name: REPORT_DESTINATION
          value: {{ .Values.global.reportDestination }}
        - name: RUST_LOG
          value: "info,command_service=debug"
        ports:
        - containerPort: 51805
      imagePullSecrets:
      - name: {{ .Values.global.cdlImagePullSecrets }}


