apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-query-service
  labels:
    app: {{ .Release.Name }}-postgres-query-service
    repository.type: document
    repository.name: postgres
spec:
  replicas: {{ .Values.queryServiceReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres-query-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres-query-service
        repository.type: document
        repository.name: postgres
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: cdl-postgres-query-service
        image: "{{ .Values.global.imageRepositoryPath }}cdl-query-service:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/query-service"]
        env:
        - name: QUERY_SERVICE_REPOSITORY_KIND
          value: 'postgres'
        - name: QUERY_SERVICE_POSTGRES__USERNAME
          value: {{ .Values.postgresUsername }}
        - name: QUERY_SERVICE_POSTGRES__PASSWORD
          value: {{ .Values.postgresPassword }}
        - name: QUERY_SERVICE_POSTGRES__HOST
          value: {{ .Values.postgresHost }}
        - name: QUERY_SERVICE_POSTGRES__PORT
          value: "{{ .Values.postgresPort }}"
        - name: QUERY_SERVICE_POSTGRES__DBNAME
          value: {{ .Values.postgresDbname }}
        - name: QUERY_SERVICE_POSTGRES__SCHEMA
          value: {{ .Values.postgresSchema }}
        - name: QUERY_SERVICE_INPUT_PORT
          value: "6400"
        - name: QUERY_SERVICE_LOG__RUST_LOG
          value: "info,query_service=debug"
        - name: QUERY_SERVICE_MONITORING__OTEL_SERVICE_NAME
          value: "postgres-query"
        ports:
        - containerPort: 51805
      imagePullSecrets:
      - name: {{ .Values.global.cdlImagePullSecrets }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-query-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-postgres-query-service
  ports:
    - port: 6400
      targetPort: 6400
