[package]
name = "rpc_dto_utils"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.0"
proc-macro-crate = "1.0.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "1.0.72", features = ["full", "extra-traits"] }
