version: "2.2"

services:
  postgres: {}

  zoo_druid:
    image: library/zookeeper:3.4.9
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo_druid:2888:3888

  coordinator:
    image: apache/druid:0.20.0
    volumes:
      - ./docker-volume/druid:/opt/data
    depends_on:
      - zoo_druid
      - postgres
    ports:
      - "8081:8081"
    command: coordinator
    env_file:
      - environment

  broker:
    image: apache/druid:0.20.0
    depends_on:
      - zoo_druid
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command: broker
    env_file:
      - environment

  historical:
    image: apache/druid:0.20.0
    volumes:
      - ./docker-volume/druid:/opt/data
    depends_on:
      - zoo_druid
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command: historical
    env_file:
      - environment

  middlemanager:
    image: apache/druid:0.20.0
    volumes:
      - ./docker-volume/druid:/opt/data
    depends_on:
      - zoo_druid
      - postgres
      - coordinator
    ports:
      - "8091:8091"
    command: middleManager
    env_file:
      - environment

  router:
    image: apache/druid:0.20.0
    depends_on:
      - zoo_druid
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command: router
    env_file:
      - environment
