apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-data-router
  labels:
    app: {{ .Release.Name }}-data-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-data-router
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-data-router
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: cdl-data-router
        image: "{{ .Values.global.imageRepositoryPath }}cdl-data-router:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/data-router"]
        env:
        - name: INPUT_TOPIC_OR_QUEUE
          value: "{{ .Values.dataRouter.inputTopicOrQueue }}"
        - name: ERROR_TOPIC_OR_EXCHANGE
          value: "{{ .Values.global.reportTopicOrExchange }}"
        {{- if eq .Values.global.communicationMethod "kafka" }}
        - name: MESSAGE_QUEUE
          value: "kafka"
        - name: KAFKA_BROKERS
          value: "{{ .Values.global.kafkaBrokers }}"
        - name: KAFKA_GROUP_ID
          value: "data-router"
        {{- else }}
        - name: MESSAGE_QUEUE
          value: "amqp"
        - name: AMQP_CONNECTION_STRING
          value: "{{ .Values.global.amqpConnectionString }}"
        - name: AMQP_CONSUMER_TAG
          value: "data-router"
        {{- end }}
        - name: SCHEMA_REGISTRY_ADDR
          value: "http://{{ .Release.Name }}-schema-registry:6400"
        - name: CACHE_CAPACITY
          value: "500"
        - name: RUST_LOG
          value: "info,data_router=debug"
        ports:
        - containerPort: 51805
      imagePullSecrets:
        - name: {{ .Values.global.cdlImagePullSecrets }}
