apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-data-router
  labels:
    app: {{ .Release.Name }}-data-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-data-router
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-data-router
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: cdl-data-router
        image: "{{ .Values.global.imageRepositoryPath }}cdl-data-router:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/data-router"]
        env:
        {{- if eq .Values.global.communicationMethod "kafka" }}
        - name: DATA_ROUTER_COMMUNICATION_METHOD
          value: "kafka"
        - name: DATA_ROUTER_KAFKA__BROKERS
          value: "{{ .Values.global.kafkaBrokers }}"
        - name: DATA_ROUTER_KAFKA__GROUP_ID
          value: "data-router"
        - name: DATA_ROUTER_KAFKA__INGEST_TOPIC
          value: "{{ .Values.dataRouter.inputSource }}"
        {{- else if eq .Values.global.communicationMethod "amqp" }}
        - name: DATA_ROUTER_COMMUNICATION_METHOD
          value: "amqp"
        - name: DATA_ROUTER_AMQP__EXCHANGE_URL
          value: "{{ .Values.global.amqpConnectionString }}"
        - name: DATA_ROUTER_AMQP__TAG
          value: "data-router"
        - name: DATA_ROUTER_AMQP__INGEST_QUEUE
          value: "{{ .Values.dataRouter.inputSource }}"
        {{- else }}
        - name: DATA_ROUTER_COMMUNICATION_METHOD
          value: "grpc"
        - name: DATA_ROUTER_GRPC__ADDRESS
          value: "0.0.0.0:6402"
        {{- end }}
        - name: DATA_ROUTER_SERVICES__SCHEMA_REGISTRY_URL
          value: "http://{{ .Release.Name }}-schema-registry:6400"
        - name: DATA_ROUTER_CACHE_CAPACITY
          value: "500"
        - name: DATA_ROUTER_LOG__RUST_LOG
          value: "info,data_router=debug"
        - name: DATA_ROUTER_MONITORING__OTEL_SERVICE_NAME
          value: "data-router"
        - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
          value: {{ .Values.global.jaegerAgentHost }}
        - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
          value: "{{ .Values.global.jaegerAgentPort }}"
        ports:
        - containerPort: 51805
      imagePullSecrets:
        - name: {{ .Values.global.cdlImagePullSecrets }}
