apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-partial-update-engine
  labels:
    app: {{ .Release.Name }}-partial-update-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-partial-update-engine
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-partial-update-engine
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: cdl-partial-update-engine
        image: "{{ .Values.global.imageRepositoryPath }}cdl-partial-update-engine:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/partial-update-engine"]
        env:
        - name: PARTIAL_UPDATE_ENGINE_COMMUNICATION_METHOD
          value: 'kafka'
        - name: PARTIAL_UPDATE_ENGINE_SERVICES__SCHEMA_REGISTRY_URL
          value: "http://{{ .Release.Name }}-schema-registry:6400"
        - name: PARTIAL_UPDATE_ENGINE_KAFKA__BROKERS
          value: "{{ .Values.global.kafkaBrokers }}"
        - name: PARTIAL_UPDATE_ENGINE_KAFKA__EGEST_TOPIC
          value: "{{ .Values.global.objectBuilderInput }}"
        - name: PARTIAL_UPDATE_ENGINE_NOTIFICATION_CONSUMER__BROKERS
          value: "{{ .Values.global.kafkaBrokers }}"
        - name: PARTIAL_UPDATE_ENGINE_NOTIFICATION_CONSUMER__SOURCE
          value: "{{ .Values.global.reportDestination }}"
        - name: PARTIAL_UPDATE_ENGINE_NOTIFICATION_CONSUMER__GROUP_ID
          value: "partial-update-engine"
        - name: PARTIAL_UPDATE_ENGINE_SLEEP_PHASE_LENGTH
          value: "{{ .Values.partialUpdateEngine.sleepPhaseLength }}"
        - name: PARTIAL_UPDATE_ENGINE_LOG__RUST_LOG
          value: "info,partial_update_engine=debug"
        - name: PARTIAL_UPDATE_ENGINE_MONITORING__OTEL_SERVICE_NAME
          value: "partial-update-engine"
        - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
          value: {{ .Values.global.jaegerAgentHost }}
        - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
          value: "{{ .Values.global.jaegerAgentPort }}"
        ports:
        - containerPort: 51805
      imagePullSecrets:
        - name: {{ .Values.global.cdlImagePullSecrets }}

