[tasks.cleanup]
script = "rm -rf www/wasm"

[tasks.pack]
script = "wasm-pack build . --target web --out-name wasm --out-dir www/wasm"

[tasks.start]
dependencies = ["pack"]
command = "http-server"
args = ["www"]
