cargo-features = ["named-profiles"]

[workspace]
members = [
  "benchmarking",
  "e2e",
  "xtask",
  "crates/*",
  "crates/utils/crates/*"
]

[profile.ci]
inherits = "dev"
debug = false
incremental = false

[profile.release]
lto = true
codegen-units = 1
