input_port = 50203

[postgres]
username = "postgres"
password = "1234"
host = "localhost"
port = "5432"
dbname = "postgres"
schema = "cdl"

[monitoring]
otel_service_name = "materializer-general"

[log]
rust_log = "info,materializer_general=debug"
