input_port = 50107
schema_registry_url = "https://localhost:50101"

[amqp]
tag = "object_builder"
ingest_queue = "cdl.materialize"

[monitoring]
otel_service_name = "object-builder"

[log]
rust_log = "info,object_builder=debug"
