global:
  imageRepositoryPath: ""
  imageVersion: latest
  imagePullPolicy: IfNotPresent
  kafkaBrokers:  infrastructure-kafka-headless
  rabbitMqConnectionString: "amqp://user:CHANGEME@infrastructure-rabbitmq:5672/%2f"
  cdlImagePullSecrets: services
  reportTopic: cdl.errors

dataRouter:
  inputQueue: cdl.data.input
  image: cdl-data-router
  bin: data-router

schemaRegistry:
  replicationTopics: cdl.schema.replication
  storageClass: standard
  storageSize: 3Gi
  port: 30150
  image: cdl-schema-registry
  bin: schema-registry

leaderElector:
  heartbeatTime: 2
  image: cdl-leader-elector
  bin: leader-elector


commandService:
  image: cld-command-service
  bin: command-service

documentStorage:
  image: cdl-document-storage
  bin: document-storage

postgres-document:
  postgresConnectionString: "postgres://postgres:CHANGEME@infrastructure-postgresql/CDL"
  postgresDbReplicaCount: 0
  inputTopic: cdl.document.data
  commandService:
    image: cld-command-service
    bin: command-service
    replicaCount: 1
  queryService:
    image: cdl-query-service
    bin: query-service
    inputPort: 50102
    replicaCount: 1

sled-document:
  replicaCommandCount: 0
  replicaDbCount: 1
  maxDbSize: 3Gi
  storageClass: standard
  inputTopic: cdl.document2.data
  documentStorage:
    image: cdl-document-storage
    bin: document-storage
  dataRouter:
    image: cdl-data-router
    bin: data-router
  commandService:
    image: cld-command-service
    bin: command-service

druid-timeseries:
  replicaCommandCount: 0
  inputTopic: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
  commandService:
    image: cld-command-service
    bin: command-service
