global:
  imageRepositoryPath: ""
  imageVersion: latest
  imagePullPolicy: IfNotPresent
  kafkaBrokers:  infrastructure-kafka-headless
  rabbitMqConnectionString: "amqp://user:CHANGEME@infrastructure-rabbitmq:5672/%2f"
  cdlImagePullSecrets: services
  reportTopic: cdl.errors

dataRouter:
  inputQueue: cdl.data.input

schemaRegistry:
  replicationTopics: cdl.schema.replication
  storageClass: standard
  storageSize: 3Gi
  port: 30150

leaderElector:
  heartbeatTime: 2



postgres-document:
  commandServiceReplicaCount: 1
  postgresDbReplicaCount: 1
  postgresConnectionString: "postgres://postgres:CHANGEME@infrastructure-postgresql/CDL"
  inputTopic: cdl.document.data

sled-document:
  replicaCommandCount: 1
  replicaDbCount: 1
  maxDbSize: 3Gi
  storageClass: standard
  inputTopic: cdl.document2.data

druid-timeseries:
  replicaCommandCount: 1
  inputTopic: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
