apiVersion: v1
kind: Pod
metadata:
  name: cdl-e2e
spec:
  containers:
  - name: e2e
    image: cdl-e2e
    imagePullPolicy: IfNotPresent
    env:
    - name: RUST_TEST_THREADS
      value: "1"
    command:
      - './e2e'
      - 'should_properly_name_fields_from_subobjects'
#      - '--nocapture'
  restartPolicy: Never
