[package]
authors = ["CDL Team"]
edition = "2018"
license = "Apache-2.0"
name = "query-service-ts"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "query_service_ts"
path = "src/lib.rs"

[[bin]]
name = "query-service-ts"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
bb8 = "0.4"
log = "0.4.11"
env_logger = "0.8.2"
reqwest = {version = "0.10", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
structopt = "0.3"
tokio = {version = "0.2", features = ["macros"]}
tonic = "0.3"
utils = {path = "../utils"}
rpc = { path = "../rpc" }
