[package]
name = "utils"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
# Workspace
rpc         = { path    = "../rpc" }
tracing_tools           = { path    = "../tracing_tools", features = ["kafka", "grpc", "http"] } # TODO: Use these feature flags

# Crates.io
anyhow      = "1.0"
async-trait = "0.1"
hyper       = "0.14.7"
lapin       = "1.7"
lazy_static = "1.4"
metrics     = { version = "0.14", features = ["std"] }
rdkafka     = { version = "0.26", features = ["cmake-build"] }
reqwest     = { version = "0.11", features = ["json"] }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = { version = "1.0", features = ["raw_value"] }
thiserror   = "1.0"
tokio       = { version = "1.5", features = ["rt-multi-thread"] }
tokio-amqp  = "1.0"
tracing     = "0.1"
url         = "2.2"
uuid        = { version = "0.8", features = ["v4", "serde"] }
vec_map     = "0.8"
async-stream            = "0.3"
futures-util            = "0.3"
tonic                   = "0.4"
tracing-futures         = "0.2"
metrics-exporter-prometheus         = "0.3"

[dev-dependencies]
test-case = "1.1"
tokio       = { version = "1.5", features = ["rt-multi-thread", "macros", "sync"] }
