name: MDBook

on:
  pull_request:
    paths:
    - "docs/**"
jobs:
  check-mdbook:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.6"

      - name: Setup linkcheck
        run: ./.github/scripts/install-executable-from-git.sh --git Michael-F-Bryan/mdbook-linkcheck --archive-type .zip --exec-name mdbook-linkcheck

      - name: Build book
        run: mdbook build
