[package]
name = "rpc"
version = "0.1.0"
authors = ["CDL Team"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "rpc"
path = "src/lib.rs"

[dependencies]
# Workspace
tracing_tools           = { path    = "../tracing_tools", features = ["grpc"] }

# Crates.io
anyhow      = "1.0"
derive_more = "0.99"
prost       = "0.7"
serde       = { version = "1.0", features = ["derive"] }
sqlx        = { version = "0.5", features = ['runtime-tokio-rustls'] }
thiserror   = "1.0"
tonic       = "0.4"
async-graphql           = { version = "2.6", features = ["uuid"] }
futures-util            = "0.3"
