[package]
name = "rpc"
version = "0.1.0"
authors = ["CDL Team"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "rpc"
path = "src/lib.rs"

[dependencies]
tonic       = "0.4"
prost       = "0.7"
anyhow      = "1.0"
thiserror   = "1.0"
sqlx        = "0.5"
serde       = { version = "1.0", features = ["derive"] }
async-graphql           = { version = "2.6", features = ["uuid"] }

[build-dependencies]
tonic-build = { version = "0.4", default-features = false, features = ["prost", "transport"] }
