communication_method = "amqp"
repository_kind = "victoria_metrics"

[services]
schema_registry_url = "http://localhost:50101"
object_builder_url = "http://localhost:50107"
edge_registry_url = "http://localhost:50110"
query_router_url = "http://localhost:50103"
on_demand_materializer_url = "http://localhost:50108"

[amqp]
exchange_url = "amqp://user:CHANGEME@localhost:5672/%2f"

[victoria_metrics]
url = "http://localhost:8428"

[notifications]
destination = "cdl.reports"

[monitoring]
metrics_port = "0" # Random
stats_port = "0" # Random
