apiVersion: v1
kind: Pod
metadata:
  name: data-injector
spec:
  restartPolicy: Never
  containers:
    - image: epiphanyservices.azurecr.io/cdl_upload_to_kafka:0.0.5
      imagePullPolicy: Always
      name: data-injector
      command:
        [
          "/bin/upload_to_kafka",
          "--brokers",
          "10.1.5.4:9092",
          "--count",
          "500000",
          "--topic",
          "cdl.input.data",
          "--schema-id",
          "f17ff366-08a0-11eb-8000-000000000000",
        ]
  imagePullSecrets:
    - name: services
