apiVersion: v1
kind: Pod
metadata:
  name: data-injector
spec:
  restartPolicy: Never
  containers:
    - image: cdl-upload-to-kafka
      imagePullPolicy: IfNotPresent
      name: data-injector
      command:
        [
          "/bin/upload-to-kafka",
          "--brokers",
          "infrastructure-kafka:9092",
          "--count",
          "10",
          "--topic",
          "cdl.data.input",
          "--schema-id",
          "a6228589-3a0f-11eb-8000-000000000000",
        ]
  imagePullSecrets:
    - name: services
