[package]
name = "api"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
# Workspace
rpc         = { path = "../rpc" }
utils       = { path = "../utils" }

# Crates.io
anyhow      = "1.0"
async-trait = "0.1"
futures     = "0.3"
itertools   = "0.10"
juniper     = { version = "0.15", features = ["uuid"] }
log         = "0.4"
num-derive  = "0.3.3"
num-traits  = "0.2.14"
semver      = { version = "0.11", features = ["serde"] }
reqwest     = { version = "0.10", features = ["json"] }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
structopt   = "0.3"
thiserror   = "1.0"
tokio       = { version = "0.2", default-features = false, features = ["sync", "rt-threaded", "macros"] }
tracing     = "0.1"
uuid        = { version = "0.8", features = ["v4", "serde"] }
warp        = "0.2"
async-stream            = "0.3"
juniper_graphql_ws      = "0.2"
juniper_warp            = { version = "0.6", features = ["subscriptions"] }
tracing-futures         = "0.2"
