input_port = 50106
insert_destination = "cdl.data.input"

[kafka]
group_id = "api"

[amqp]
tag = "api"

[notification_consumer]
source = "cdl.reports"

[monitoring]
otel_service_name = "api"

[log]
rust_log = "info,api=debug"
