[tasks.pack-wasm]
script = "wasm-pack build frontend/ --target web --out-name wasm --out-dir output/"

[tasks.move-wasm]
dependencies = ["pack-wasm"]
script = "mv frontend/output static/wasm"

[tasks.clean-wasm]
script = "rm -rf static/wasm"

[tasks.build]
dependencies = ["clean-wasm", "move-wasm"]
command = "cargo"
args = ["build"]

[tasks.start]
dependencies = ["build"]
command = "cargo"
args = ["run", "--bin", "mnemosyne-server"]
