global:
  imageRepositoryPath: ""
  imageVersion: latest
  imagePullPolicy: IfNotPresent
  kafkaBrokers:  infrastructure-kafka-headless
  cdlImagePullSecrets: services
  reportTopic: cdl.errors
  rabbitConnectionString: "amqp://user:CHANGEME@infrastructure-rabbitmq:5672/%2f"

dataRouter:
  inputTopic: cdl.data.input

schemaRegistry:
  replicationTopics: cdl.schema.replication
  storageClass: standard
  storageSize: 3Gi
  port: 30150

leaderElector:
  heartbeatTime: 2

postgres-document:
  commandServiceReplicaCount: 1
  postgresDbReplicaCount: 1
  postgresConnectionString: "postgres://postgres:CHANGEME@infrastructure-postgresql/CDL"
  postgresUsername: postgres
  postgresPassword: CHANGEME
  postgresHost: infrastructure-postgresql
  postgresPort: 5432
  postgresDbname: CDL
  postgresSchema: public
  ingestionMethod: MessageQueue
  inputTopic: cdl.document.data

sled-document:
  replicaCommandCount: 1
  replicaDbCount: 1
  maxDbSize: 3Gi
  storageClass: standard
  inputTopic: cdl.document2.data
  ingestionMethod: MessageQueue

druid-timeseries:
  replicaCommandCount: 1
  inputTopic: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
  ingestionMethod: MessageQueue

victoria-metrics-timeseries:
  replicaCommandCount: 1
  inputTopic: cdl.timeseries2.data
  ingestionMethod: MessageQueue
  outputURL: http://infrastructure-victoria-metrics-single-server:8428/
