global:
  imageRepositoryPath: epiphanyplatform/
  imageVersion: master
  imagePullPolicy: Always
  communicationMethod: "kafka"
  kafkaBrokers: 10.1.5.4:9092
  amqpConnectionString: "amqp://rabbitmq:rabbitmq@10.1.1.4:5672/%2f"
  cdlImagePullSecrets: services
  reportTopicOrExchange: cdl.errors

api:
  port: 30152

dataRouter:
  inputTopicOrQueue: cdl.data.input
  multitasking: true

leaderElector:
  heartbeatTime: 2

queryRouter:
  port: 30153

schemaRegistry:
  storageClass: standard
  storageSize: 3Gi
  port: 30150

webAdmin:
  port: 30151

postgres-document:
  commandServiceReplicaCount: 1
  queryServiceReplicaCount: 1
  postgresUsername: postgres
  postgresPassword: postgres
  postgresHost: 10.1.1.5
  postgresPort: 5432
  postgresDbname: cdldb
  postgresSchema: public
  inputTopicOrQueue: cdl.document.data

druid-timeseries:
  replicaCommandCount: 0
  queryServiceReplicaCount: 0
  inputTopicOrQueue: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
  queryURL: 
  tableName: CDL

victoria-metrics-timeseries:
  replicaCommandCount: 0
  queryServiceReplicaCount: 0
  inputTopicOrQueue: cdl.timeseries2.data
  outputURL: http://infrastructure-victoria-metrics-single-server:8428/
