routing_cache_capacity = 1000
async_task_limit = 32

[kafka]
ingest_topic = "cdl.data.input"
group_id = "data_router"

[monitoring]
otel_service_name = "data-router"

[validation]
enabled = false
cache_capacity = 1024

[log]
rust_log = "info,data_router=debug"
