input_port = 50101
import_file = "../compose/setup/schema_registry/initial_schema.mq.json"

[kafka]
group_id = "schema_registry"

[monitoring]
otel_service_name = "schema-registry"

[log]
rust_log = "info,schema_registry=debug"
