cache_capacity = 1000
async_task_limit = 32
send_to = "cdl.data.input"

[kafka]
ingest_topic = "cdl.data.validate"
group_id = "validator"

[monitoring]
otel_service_name = "validator"

[log]
rust_log = "info,validator=debug"
