name: Check the MDBook

on:
  pull_request:
    paths:
    - 'docs/**'
jobs:
  check-mdbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.6'

      - name: Setup linkcheck
        run: curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git Michael-F-Bryan/mdbook-linkcheck

      - name: Build book
        run: mdbook build
