name: Publish

on:
  push:
    tags:
      - "*"
    branches:
      - "develop"
    paths:
      - "crates"
      - "web-admin"
      - "build.sh"
      - "Dockerfile"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain"

jobs:
  build-and-deploy:
    name: docker.io
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Login to registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build and push crates
      run: |
        crates=(command-service data-router leader-elector query-service query-service-ts schema-registry query-router api edge-registry partial-update-engine object-builder materializer)
        for crate in "${crates[@]}"
        do
        docker build . --build-arg BIN=$crate -t epiphanyplatform/cdl-$crate:${{ steps.get_version.outputs.VERSION }}
        docker tag epiphanyplatform/cdl-$crate:${{ steps.get_version.outputs.VERSION }} epiphanyplatform/cdl-$crate:latest
        docker push epiphanyplatform/cdl-$crate:${{ steps.get_version.outputs.VERSION }}
        docker push epiphanyplatform/cdl-$crate:latest
        done
      env:
        DOCKER_BUILDKIT: 1

    - name: Build and push web-admin
      run: |
        cd web-admin
        docker build . -t epiphanyplatform/cdl-web-admin:${{ steps.get_version.outputs.VERSION }}
        docker tag epiphanyplatform/cdl-web-admin:${{ steps.get_version.outputs.VERSION }} epiphanyplatform/cdl-web-admin:latest
        docker push epiphanyplatform/cdl-web-admin:${{ steps.get_version.outputs.VERSION }}
        docker push epiphanyplatform/cdl-web-admin:latest
