name: Publish to Azure on Release

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - cdl
          - command_service
          - data_router
          - document_storage
          - leader_elector
          - query_router
          - query_service
          - schema_registry
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Build and push image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_DOMAIN }}
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}
    - run: |
        docker build . --build-arg BIN=${{ matrix.crate }} -t ${{ secrets.AZURE_DOMAIN }}/${{ matrix.crate }}:${{ github.sha }}
        docker push ${{ secrets.AZURE_DOMAIN }}/${{ matrix.crate }}:${{ github.sha }}
