name: Release Nightly
on:
  push:
    branches:
      - 'develop'


# its negativbe matching patterns,
# it would be optimal to exclude all branches that are not release or develop branches
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns

jobs:
  build-and-push:
    name: build nightly and push to registry
    runs-on: ubuntu-latest
    steps:

    - name: Login to registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push crates
      run: |
        crates=(data-router command-service query-router query-service query-service-ts schema-registry api edge-registry partial-update-engine object-builder materializer-general materializer-ondemand)
        for crate in "${crates[@]}"
        do
          echo "building ${crate}
          docker build . --build-arg BIN=$crate -t "epiphanyplatform/cdl-${crate}:lastest"
          docker tag "epiphanyplatform/cdl-${crate}:latest"
          docker push "epiphanyplatform/cdl-${crate}:latest"
        done
      env:
        DOCKER_BUILDKIT: 1

    - name: Build and push web-admin
      run: |
        VERSION_LONG=${{ steps.checkpoint.outputs.version }}
        VERSION_SHORT=$(echo ${VERSION_LONG} | cut -d '.' -f -2)
        cd web-admin
        docker build . -t "epiphanyplatform/cdl-web-admin:latest"
        docker tag "epiphanyplatform/cdl-web-admin:latest"
        docker push "epiphanyplatform/cdl-web-admin:latest"

