name: 'Security audit (periodic)'
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - devel
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}