name: Audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

---
name: Audit
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  security_audit:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - develop
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
