name: dockerhub test workflow

on: [ push ]

jobs:
  build-and-deploy:
    name: test if docker workflow is working
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Login to registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push one crate
      run: |
        crate="materializer-ondemand"
        version="dev-$(date -u +'%Y-%m-%d')-senko"

        docker build . --build-arg BIN=$crate -t epiphanyplatform/cdl-$crate:${version}
        docker tag epiphanyplatform/cdl-$crate:${version} epiphanyplatform/cdl-$crate:esavier-senko-latest
        docker push epiphanyplatform/cdl-$crate:$version
        docker push epiphanyplatform/cdl-$crate:esavier-senko-latest
      env:
        DOCKER_BUILDKIT: 1
